name: Conflict Detection

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for merge conflicts
        id: conflicts
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const mergeable = response.data.mergeable;
            if (mergeable === false) {
              console.log("Conflict detected in pull request #" + context.issue.number);
              return "true";
            } else {
              console.log("No conflict detected in pull request #" + context.issue.number);
              return "false";
            }
          result-encoding: string

      # Contoh notifikasi console, ganti dengan action notifikasi yang sesuai
      - name: Log conflict notification
        if: steps.conflicts.outputs.result == 'true'
        run: echo "Conflict detected. Action required."