name: Auto Pull Request to Master

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "bryanathallah7@gmail.com"
          git config --global user.name "Bryan Athallah"

      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: 'develop'
          path: 'develop'

      - name: Attempt to merge develop into master
        id: merge_attempt
        run: |
          cd develop
          git fetch origin master
          git checkout -b temp-merge-branch
          # Coba merge dan simpan output ke file untuk dianalisis
          if git merge origin/master --no-commit --no-ff --allow-unrelated-histories >merge_output.txt 2>&1; then
            echo "Merge succeeded with no conflicts."
            echo "::set-output name=merge_status::success"
          else
            echo "Merge failed with conflicts."
            echo "::set-output name=merge_status::conflict"
            echo "::set-output name=merge_message::${merge_message}"
            git --no-pager diff --name-only --diff-filter=U
            merge_message=$(<merge_output.txt)
          fi
        shell: bash

      - name: Handle merge conflicts
        if: steps.merge_attempt.outputs.merge_status == 'conflict'
        run: |
          echo "Handling merge conflict..."
          echo "Conflict details:"
          # echo "${{ steps.merge_attempt.outputs.merge_message }}"  # Menampilkan pesan konflik yang disimpan
          echo "${{ steps.merge_attempt.outputs.name }}"  # Menampilkan pesan konflik yang disimpan
          # Tambahkan tindakan khusus yang ingin Anda jalankan jika terjadi konflik

      - name: Handle successful merge
        if: steps.merge_attempt.outputs.merge_status == 'success'
        run: |
          echo "Merge was successful. Proceeding with the workflow..."
          # Tambahkan tindakan yang ingin Anda jalankan jika merge berhasil

      - name: Create Pull Request
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: develop
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Auto PR: Merge develop into master"
          pr_body: |
            This is an automatically generated pull request to merge changes from `develop` into `master`.
          pr_draft: false
          pr_label: "auto-merge"

      - name: OUTPUR PR NUMBER
        run: echo "The PR Number is ${{ steps.create_pr.outputs.pr_number}}"

      - name: Create Task in ClickUp with PR Number
        env:
          PR_NUMBER: ${{ steps.create_pr.outputs.pr_number }}
        run: |
          curl -X POST https://api.clickup.com/api/v2/list/901804076439/task \
          -H "Authorization: ${{ secrets.CLICKUP_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "PR #'${PR_NUMBER}' Task",
            "description": "This task is associated with PR number '${PR_NUMBER}'",
            "status": "open",
            "assignees": [90602611],
            "custom_fields": [
              {
                "id": "8b298a3f-2e44-4b69-b7ef-9769f1417bd8",
                "value": "'${PR_NUMBER}'"
              }
            ]
          }'